# Cortex 3 — configuration for SentriX docker-compose

search {
  index = cortex
  uri = "http://elasticsearch:9200"
}

play.http.secret.key: "SentriX-Cortex-Secret-ChangeMeInProduction-2025"

cache.job = 10 minutes

job {
  timeout = 30 minutes
  directory = /tmp/cortex-jobs
}

analyzer {
  urls = [
    "https://download.thehive-project.org/analyzers.json"
  ]
  fork-join-executor {
    parallelism-min = 2
    parallelism-factor = 2.0
    parallelism-max = 4
  }
}

responder {
  urls = [
    "https://download.thehive-project.org/responders.json"
  ]
}
