# TheHive 5 — configuration for SentriX docker-compose

db.janusgraph {
  storage {
    backend: cql
    hostname: ["cassandra"]
    cql {
      cluster-name: thp
      keyspace: thehive
    }
  }
  index.search {
    backend: elasticsearch
    hostname: ["elasticsearch"]
    index-name: thehive
  }
}

storage {
  provider: localfs
  localfs.location: /opt/thp/thehive/files
}

play.http.secret.key: "SentriX-TheHive-Secret-ChangeMeInProduction-2025"
play.http.parser.maxMemoryBuffer: 256m
application.baseUrl = "http://localhost:9000"
